databaseChangeLog:
  - property:
      name: now
      value: "current_timestamp"
      dbms: "postgresql"
  - property:
      name: floatType
      value: "float4"
      dbms: "postgresql"
  - property:
      name: clobType
      value: "clob"
      dbms: "postgresql"
  - property:
      name: blobType
      value: "blob"
      dbms: "postgresql"
  - property:
      name: uuidType
      value: "uuid"
      dbms: "postgresql"
  - property:
      name: datetimeType
      value: "datetime"
      dbms: "postgresql"
  - property:
      name: timeType
      value: "time(6)"
      dbms: "postgresql"
  - include:
      file: config/liquibase/202504092200_create_tables.yaml
      relativeToChangelogFile: false
